// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    [IsForm(typeof(FloorFormType), typeof(CorrugatedSteelItem))]
    public partial class CorrugatedSteelFloorBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(CorrugatedSteelItem); } }
    }


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    [IsForm(typeof(WallFormType), typeof(CorrugatedSteelItem))]
    public partial class CorrugatedSteelWallBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(CorrugatedSteelItem); } }
    }


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    [IsForm(typeof(CubeFormType), typeof(CorrugatedSteelItem))]
    public partial class CorrugatedSteelCubeBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(CorrugatedSteelItem); } }
    }


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    [IsForm(typeof(RoofFormType), typeof(CorrugatedSteelItem))]
    public partial class CorrugatedSteelRoofBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(CorrugatedSteelItem); } }
    }


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    [IsForm(typeof(ColumnFormType), typeof(CorrugatedSteelItem))]
    public partial class CorrugatedSteelColumnBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(CorrugatedSteelItem); } }
    }


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    [IsForm(typeof(WindowFormType), typeof(CorrugatedSteelItem))]
    public partial class CorrugatedSteelWindowBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(CorrugatedSteelItem); } }
    }


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    [IsForm(typeof(RoadBarrierFormType), typeof(CorrugatedSteelItem))]
    public partial class CorrugatedSteelRoadBarrierBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(CorrugatedSteelItem); } }
    }



    [RotatedVariants(typeof(CorrugatedSteelStairsBlock), typeof(CorrugatedSteelStairs90Block), typeof(CorrugatedSteelStairs180Block), typeof(CorrugatedSteelStairs270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    [IsForm(typeof(StairsFormType), typeof(CorrugatedSteelItem))]
    public partial class CorrugatedSteelStairsBlock : Block
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    public partial class CorrugatedSteelStairs90Block : Block
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    public partial class CorrugatedSteelStairs180Block : Block
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    public partial class CorrugatedSteelStairs270Block : Block
    { }


    [RotatedVariants(typeof(CorrugatedSteelLadderBlock), typeof(CorrugatedSteelLadder90Block), typeof(CorrugatedSteelLadder180Block), typeof(CorrugatedSteelLadder270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    [IsForm(typeof(LadderFormType), typeof(CorrugatedSteelItem))]
    public partial class CorrugatedSteelLadderBlock : Block
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    public partial class CorrugatedSteelLadder90Block : Block
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    public partial class CorrugatedSteelLadder180Block : Block
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(3)] 
    public partial class CorrugatedSteelLadder270Block : Block
    { }

}
