// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    [IsForm(typeof(FloorFormType), typeof(HardwoodLumberItem))]
    public partial class HardwoodLumberFloorBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(HardwoodLumberItem); } }
    }


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    [IsForm(typeof(WallFormType), typeof(HardwoodLumberItem))]
    public partial class HardwoodLumberWallBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(HardwoodLumberItem); } }
    }


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    [IsForm(typeof(CubeFormType), typeof(HardwoodLumberItem))]
    public partial class HardwoodLumberCubeBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(HardwoodLumberItem); } }
    }


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    [IsForm(typeof(RoofFormType), typeof(HardwoodLumberItem))]
    public partial class HardwoodLumberRoofBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(HardwoodLumberItem); } }
    }


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    [IsForm(typeof(ColumnFormType), typeof(HardwoodLumberItem))]
    public partial class HardwoodLumberColumnBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(HardwoodLumberItem); } }
    }


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    [IsForm(typeof(WindowFormType), typeof(HardwoodLumberItem))]
    public partial class HardwoodLumberWindowBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(HardwoodLumberItem); } }
    }


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    [IsForm(typeof(FenceFormType), typeof(HardwoodLumberItem))]
    public partial class HardwoodLumberFenceBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(HardwoodLumberItem); } }
    }


    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    [IsForm(typeof(WindowGrillesFormType), typeof(HardwoodLumberItem))]
    public partial class HardwoodLumberWindowGrillesBlock :
        Block, IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(HardwoodLumberItem); } }
    }



    [RotatedVariants(typeof(HardwoodLumberStairsBlock), typeof(HardwoodLumberStairs90Block), typeof(HardwoodLumberStairs180Block), typeof(HardwoodLumberStairs270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    [IsForm(typeof(StairsFormType), typeof(HardwoodLumberItem))]
    public partial class HardwoodLumberStairsBlock : Block
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    public partial class HardwoodLumberStairs90Block : Block
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    public partial class HardwoodLumberStairs180Block : Block
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    public partial class HardwoodLumberStairs270Block : Block
    { }


    [RotatedVariants(typeof(HardwoodLumberLadderBlock), typeof(HardwoodLumberLadder90Block), typeof(HardwoodLumberLadder180Block), typeof(HardwoodLumberLadder270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    [IsForm(typeof(LadderFormType), typeof(HardwoodLumberItem))]
    public partial class HardwoodLumberLadderBlock : Block
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    public partial class HardwoodLumberLadder90Block : Block
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    public partial class HardwoodLumberLadder180Block : Block
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption] 
    [BlockTier(2)] 
    public partial class HardwoodLumberLadder270Block : Block
    { }

}
