// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;

    [RequiresSkill(typeof(LoggingSkill), 0)]      
    public partial class DendrologyResearchPaperBasicRecipe :
        RecipeFamily
    {
        public DendrologyResearchPaperBasicRecipe()
        {
            this.Initialize(Localizer.DoStr("Dendrology Research Paper Basic"), typeof(DendrologyResearchPaperBasicRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "DendrologyResearchPaperBasic",
                    Localizer.DoStr("Dendrology Research Paper Basic"),
                    new IngredientElement[]
                    {
                    new IngredientElement("Wood", 20, typeof(LoggingSkill)),    
                    },
                    new CraftingElement[]
                    {
                    new CraftingElement<DendrologyResearchPaperBasicItem>(), 
                    }
                )
            };


            this.ExperienceOnCraft = 2;  

            this.LaborInCalories = CreateLaborInCaloriesValue(50, typeof(LoggingSkill), typeof(DendrologyResearchPaperBasicRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(1);
            this.Initialize(Localizer.DoStr("Dendrology Research Paper Basic"), typeof(DendrologyResearchPaperBasicRecipe));

            CraftingComponent.AddRecipe(typeof(ResearchTableObject), this);
        }
    }

    [Serialized]
    [LocDisplayName("Dendrology Research Paper Basic")]
    [Weight(10)]      
    [Ecopedia("Items", "Research Papers", createAsSubPage: true, display: InPageTooltip.DynamicTooltip)]                                                                           
    [Tag("Basic Research", 1)]
    [Tag("Research", 1)]                                 
    public partial class DendrologyResearchPaperBasicItem :
    Item                                    
    {
        public override LocString DisplayDescription { get { return Localizer.DoStr("A document containing important research information. Used to discover new skills at the research table."); } }
    }
}
