// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(MillingSkill), 1)] 
    public class BeetSugarRecipe :
        RecipeFamily
    {
        public BeetSugarRecipe()
        {
            this.Initialize(Localizer.DoStr("Beet Sugar"), typeof(BeetSugarRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "BeetSugar",
                    Localizer.DoStr("Beet Sugar"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(BeetItem), 6, typeof(MillingSkill), typeof(MillingLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<SugarItem>(3),  
    
                    })
            };
            this.ExperienceOnCraft = 0.5f;  
            this.LaborInCalories = CreateLaborInCaloriesValue(80, typeof(MillingSkill), typeof(BeetSugarRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(BeetSugarRecipe), this.UILink(), 2, typeof(MillingSkill), typeof(MillingFocusedSpeedTalent), typeof(MillingParallelSpeedTalent));     
            CraftingComponent.AddRecipe(typeof(MillObject), this);
        }
    }
}
