// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(ButcherySkill), 1)] 
    public class ButcherTinyLeatherAnimalRecipe :
        RecipeFamily
    {
        public ButcherTinyLeatherAnimalRecipe()
        {
            this.Initialize(Localizer.DoStr("Butcher Tiny Leather Animal"), typeof(ButcherTinyLeatherAnimalRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "ButcherTinyLeatherAnimal",
                    Localizer.DoStr("Butcher Tiny Leather Animal"),
                    new IngredientElement[]
                    {
               new IngredientElement("TinyLeatherCarcass", 1, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<RawMeatItem>(1), 
               new CraftingElement<LeatherHideItem>(1),  
    
                    })
            };
            this.ExperienceOnCraft = 3;  
            this.LaborInCalories = CreateLaborInCaloriesValue(60, typeof(ButcherySkill), typeof(ButcherTinyLeatherAnimalRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(ButcherTinyLeatherAnimalRecipe), this.UILink(), 0.2f, typeof(ButcherySkill), typeof(ButcheryFocusedSpeedTalent), typeof(ButcheryParallelSpeedTalent));     
            CraftingComponent.AddRecipe(typeof(ButcheryTableObject), this);
        }
    }
}
