// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(ButcherySkill), 2)] 
    public class ButcherMediumAnimalRecipe :
        RecipeFamily
    {
        public ButcherMediumAnimalRecipe()
        {
            this.Initialize(Localizer.DoStr("Butcher Medium Animal"), typeof(ButcherMediumAnimalRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "ButcherMediumAnimal",
                    Localizer.DoStr("Butcher Medium Animal"),
                    new IngredientElement[]
                    {
               new IngredientElement("MediumCarcass", 1, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<RawMeatItem>(5), 
               new CraftingElement<LeatherHideItem>(1), 
               new CraftingElement<TallowItem>(1),  
    
                    })
            };
            this.ExperienceOnCraft = 9;  
            this.LaborInCalories = CreateLaborInCaloriesValue(100, typeof(ButcherySkill), typeof(ButcherMediumAnimalRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(ButcherMediumAnimalRecipe), this.UILink(), 1.5f, typeof(ButcherySkill), typeof(ButcheryFocusedSpeedTalent), typeof(ButcheryParallelSpeedTalent));     
            CraftingComponent.AddRecipe(typeof(ButcheryTableObject), this);
        }
    }
}
