// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(ButcherySkill), 1)] 
    public class ButcherSmallAnimalRecipe :
        RecipeFamily
    {
        public ButcherSmallAnimalRecipe()
        {
            this.Initialize(Localizer.DoStr("Butcher Small Animal"), typeof(ButcherSmallAnimalRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "ButcherSmallAnimal",
                    Localizer.DoStr("Butcher Small Animal"),
                    new IngredientElement[]
                    {
               new IngredientElement("SmallCarcass", 1, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<RawMeatItem>(2), 
               new CraftingElement<FurPeltItem>(2),  
    
                    })
            };
            this.ExperienceOnCraft = 4;  
            this.LaborInCalories = CreateLaborInCaloriesValue(80, typeof(ButcherySkill), typeof(ButcherSmallAnimalRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(ButcherSmallAnimalRecipe), this.UILink(), 1.2f, typeof(ButcherySkill), typeof(ButcheryFocusedSpeedTalent), typeof(ButcheryParallelSpeedTalent));     
            CraftingComponent.AddRecipe(typeof(ButcheryTableObject), this);
        }
    }
}
