// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(ButcherySkill), 3)] 
    public class ButcherBisonRecipe :
        RecipeFamily
    {
        public ButcherBisonRecipe()
        {
            this.Initialize(Localizer.DoStr("Butcher Bison"), typeof(ButcherBisonRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "ButcherBison",
                    Localizer.DoStr("Butcher Bison"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(BisonCarcassItem), 1, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<RawMeatItem>(10), 
               new CraftingElement<LeatherHideItem>(2), 
               new CraftingElement<TallowItem>(2),  
    
                    })
            };
            this.ExperienceOnCraft = 15;  
            this.LaborInCalories = CreateLaborInCaloriesValue(160, typeof(ButcherySkill), typeof(ButcherBisonRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(ButcherBisonRecipe), this.UILink(), 2.5f, typeof(ButcherySkill), typeof(ButcheryFocusedSpeedTalent), typeof(ButcheryParallelSpeedTalent));     
            CraftingComponent.AddRecipe(typeof(ButcheryTableObject), this);
        }
    }
}
