// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    public class CharredMortarRecipe :
        RecipeFamily
    {
        public CharredMortarRecipe()
        {
            this.Initialize(Localizer.DoStr("Charred Mortar"), typeof(CharredMortarRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "CharredMortar",
                    Localizer.DoStr("Charred Mortar"),
                    new IngredientElement[]
                    {
               new IngredientElement("NaturalFiber", 5, true),  
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<MortarItem>(1),  
                    })
            };
            this.LaborInCalories = CreateLaborInCaloriesValue(20); 
            this.CraftMinutes = CreateCraftTimeValue(0.16f);
            CraftingComponent.AddRecipe(typeof(CampfireObject), this);
        }
    }
}
