// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    public class CleanBlueSharkRecipe :
        RecipeFamily
    {
        public CleanBlueSharkRecipe()
        {
            this.Initialize(Localizer.DoStr("Clean Blue Shark"), typeof(CleanBlueSharkRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "CleanBlueShark",
                    Localizer.DoStr("Clean Blue Shark"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(BlueSharkItem), 1, true),  
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<RawFishItem>(8),  
                    })
            };
            this.LaborInCalories = CreateLaborInCaloriesValue(30); 
            this.CraftMinutes = CreateCraftTimeValue(4);
            CraftingComponent.AddRecipe(typeof(FisheryObject), this);
        }
    }
}
