// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(MiningSkill), 1)] 
    public class CrushedBasaltLv2Recipe :
        RecipeFamily
    {
        public CrushedBasaltLv2Recipe()
        {
            this.Initialize(Localizer.DoStr("Crushed Basalt Lv2"), typeof(CrushedBasaltLv2Recipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "CrushedBasaltLv2",
                    Localizer.DoStr("Crushed Basalt Lv2"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(BasaltItem), 20, true),  
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<CrushedBasaltItem>(5),  
    
                    })
            };
            this.ExperienceOnCraft = 0.5f;  
            this.LaborInCalories = CreateLaborInCaloriesValue(500, typeof(MiningSkill), typeof(CrushedBasaltLv2Recipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(CrushedBasaltLv2Recipe), this.UILink(), 5, typeof(MiningSkill));     
            CraftingComponent.AddRecipe(typeof(StampMillObject), this);
        }
    }
}
