// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(BakingSkill), 1)] 
    public class CulinaryResearchPaperAdvancedMeatRecipe :
        RecipeFamily
    {
        public CulinaryResearchPaperAdvancedMeatRecipe()
        {
            this.Initialize(Localizer.DoStr("Culinary Research Paper Advanced Meat"), typeof(CulinaryResearchPaperAdvancedMeatRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "CulinaryResearchPaperAdvancedMeat",
                    Localizer.DoStr("Culinary Research Paper Advanced Meat"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(BakedMeatItem), 20, typeof(BakingSkill), typeof(BakingLavishResourcesTalent)), 
               new IngredientElement(typeof( SimmeredMeatItem), 10, typeof(BakingSkill), typeof(BakingLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<CulinaryResearchPaperAdvancedItem>(1),  
    
                    })
            };
            this.ExperienceOnCraft = 0.5f;  
            this.LaborInCalories = CreateLaborInCaloriesValue(200, typeof(BakingSkill), typeof(CulinaryResearchPaperAdvancedMeatRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(CulinaryResearchPaperAdvancedMeatRecipe), this.UILink(), 1, typeof(BakingSkill), typeof(BakingFocusedSpeedTalent), typeof(BakingParallelSpeedTalent));     
            CraftingComponent.AddRecipe(typeof(ResearchTableObject), this);
        }
    }
}
