// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(CampfireCookingSkill), 1)] 
    public class CulinaryResearchPaperBasicMeatRecipe :
        RecipeFamily
    {
        public CulinaryResearchPaperBasicMeatRecipe()
        {
            this.Initialize(Localizer.DoStr("Culinary Research Paper Basic Meat"), typeof(CulinaryResearchPaperBasicMeatRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "CulinaryResearchPaperBasicMeat",
                    Localizer.DoStr("Culinary Research Paper Basic Meat"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(CharredMeatItem), 20, typeof(CampfireCookingSkill), typeof(CampfireCookingLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<CulinaryResearchPaperBasicItem>(1),  
    
                    })
            };
            this.ExperienceOnCraft = 0.5f;  
            this.LaborInCalories = CreateLaborInCaloriesValue(50, typeof(CampfireCookingSkill), typeof(CulinaryResearchPaperBasicMeatRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(CulinaryResearchPaperBasicMeatRecipe), this.UILink(), 1, typeof(CampfireCookingSkill), typeof(CampfireCookingFocusedSpeedTalent), typeof(CampfireCookingParallelSpeedTalent));     
            CraftingComponent.AddRecipe(typeof(ResearchTableObject), this);
        }
    }
}
