// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    public class DirtRampBasicRecipe :
        RecipeFamily
    {
        public DirtRampBasicRecipe()
        {
            this.Initialize(Localizer.DoStr("Dirt Ramp Basic"), typeof(DirtRampBasicRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "DirtRampBasic",
                    Localizer.DoStr("Dirt Ramp Basic"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(DirtItem), 6),   
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<DirtRampItem>(1),  
                    })
            };
            this.LaborInCalories = CreateLaborInCaloriesValue(20); 
            this.CraftMinutes = CreateCraftTimeValue(0.5f);
            CraftingComponent.AddRecipe(typeof(WorkbenchObject), this);
        }
    }
}
