// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    public class HardwoodBoardsRecipe :
        Recipe
    {
        public HardwoodBoardsRecipe()
        {
            var product = new Recipe(
                "HardwoodBoards",
                Localizer.DoStr("Hardwood Boards"),
                new IngredientElement[]
                {
               new IngredientElement(typeof(HardwoodHewnLogItem), 1),   
                },
               new CraftingElement<HardwoodBoardItem>(1)
            );
            CraftingComponent.AddTagProduct(typeof(WorkbenchObject), typeof(BoardsRecipe), product);
        }
    }
}
