// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    public class HewnLogDoorRecipe :
        RecipeFamily
    {
        public HewnLogDoorRecipe()
        {
            this.Initialize(Localizer.DoStr("Hewn Log Door"), typeof(HewnLogDoorRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "HewnLogDoor",
                    Localizer.DoStr("Hewn Log Door"),
                    new IngredientElement[]
                    {
               new IngredientElement("HewnLog", 5),   
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<HewnDoorItem>(1),  
                    })
            };
            this.LaborInCalories = CreateLaborInCaloriesValue(100); 
            this.CraftMinutes = CreateCraftTimeValue(2);
            CraftingComponent.AddRecipe(typeof(WorkbenchObject), this);
        }
    }
}
