// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    public class MortaredStonesRecipe :
        RecipeFamily
    {
        public MortaredStonesRecipe()
        {
            this.Initialize(Localizer.DoStr("Mortared Stones"), typeof(MortaredStonesRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "MortaredStones",
                    Localizer.DoStr("Mortared Stones"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(MortarItem), 1),   
               new IngredientElement("Rock", 6),   
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<MortaredStoneItem>(1),  
                    })
            };
            this.LaborInCalories = CreateLaborInCaloriesValue(30); 
            this.CraftMinutes = CreateCraftTimeValue(0.25f);
            CraftingComponent.AddRecipe(typeof(WorkbenchObject), this);
        }
    }
}
