// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(AdvancedCookingSkill), 1)] 
    public class RefineTallowRecipe :
        RecipeFamily
    {
        public RefineTallowRecipe()
        {
            this.Initialize(Localizer.DoStr("Refine Tallow"), typeof(RefineTallowRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "RefineTallow",
                    Localizer.DoStr("Refine Tallow"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(TallowItem), 18, typeof(AdvancedCookingSkill), typeof(AdvancedCookingLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<OilItem>(1),  
    
                    })
            };
            this.ExperienceOnCraft = 0.5f;  
            this.LaborInCalories = CreateLaborInCaloriesValue(30, typeof(AdvancedCookingSkill), typeof(RefineTallowRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(RefineTallowRecipe), this.UILink(), 0.8f, typeof(AdvancedCookingSkill), typeof(AdvancedCookingFocusedSpeedTalent), typeof(AdvancedCookingParallelSpeedTalent));     
            CraftingComponent.AddRecipe(typeof(StoveObject), this);
        }
    }
}
