// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(CuttingEdgeCookingSkill), 1)] 
    public class RefineMeatRecipe :
        RecipeFamily
    {
        public RefineMeatRecipe()
        {
            this.Initialize(Localizer.DoStr("Refine Meat"), typeof(RefineMeatRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "RefineMeat",
                    Localizer.DoStr("Refine Meat"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(RawMeatItem), 16, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<HydrocolloidsItem>(1),  
    
                    })
            };
            this.ExperienceOnCraft = 1;  
            this.LaborInCalories = CreateLaborInCaloriesValue(40, typeof(CuttingEdgeCookingSkill), typeof(RefineMeatRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(RefineMeatRecipe), this.UILink(), 2, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingFocusedSpeedTalent), typeof(CuttingEdgeCookingParallelSpeedTalent));     
            CraftingComponent.AddRecipe(typeof(LaboratoryObject), this);
        }
    }
}
