// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(CampfireCookingSkill), 1)] 
    public class RenderFatRecipe :
        RecipeFamily
    {
        public RenderFatRecipe()
        {
            this.Initialize(Localizer.DoStr("Render Fat"), typeof(RenderFatRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "RenderFat",
                    Localizer.DoStr("Render Fat"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(RawMeatItem), 3, typeof(CampfireCookingSkill), typeof(CampfireCookingLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<TallowItem>(2),  
    
                    })
            };
            this.ExperienceOnCraft = 0.5f;  
            this.LaborInCalories = CreateLaborInCaloriesValue(30, typeof(CampfireCookingSkill), typeof(RenderFatRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(RenderFatRecipe), this.UILink(), 0.8f, typeof(CampfireCookingSkill), typeof(CampfireCookingFocusedSpeedTalent), typeof(CampfireCookingParallelSpeedTalent));     
            CraftingComponent.AddRecipe(typeof(CampfireObject), this);
        }
    }
}
