// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(MiningSkill), 1)] 
    public class SandConcentrateRecipe :
        RecipeFamily
    {
        public SandConcentrateRecipe()
        {
            this.Initialize(Localizer.DoStr("Sand Concentrate"), typeof(SandConcentrateRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "SandConcentrate",
                    Localizer.DoStr("Sand Concentrate"),
                    new IngredientElement[]
                    {
               new IngredientElement("Silica", 2, typeof(MiningSkill)),    
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<SandItem>(1),  
    
                    })
            };
            this.ExperienceOnCraft = 0.5f;  
            this.LaborInCalories = CreateLaborInCaloriesValue(40, typeof(MiningSkill), typeof(SandConcentrateRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(SandConcentrateRecipe), this.UILink(), 1, typeof(MiningSkill));     
            CraftingComponent.AddRecipe(typeof(RockerBoxObject), this);
        }
    }
}
