// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(CarpentrySkill), 1)] 
    public class SawSoftwoodBoardsRecipe :
        Recipe
    {
        public SawSoftwoodBoardsRecipe()
        {
            var product = new Recipe(
                "SawSoftwoodBoards",
                Localizer.DoStr("Saw Softwood Boards"),
                new IngredientElement[]
                {
               new IngredientElement(typeof(SoftwoodHewnLogItem), 2, typeof(CarpentrySkill), typeof(CarpentryLavishResourcesTalent)),    
                },
               new CraftingElement<SoftwoodBoardItem>(3)
            );
            CraftingComponent.AddTagProduct(typeof(SawmillObject), typeof(SawBoardsRecipe), product);
        }
    }
}
