// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(PotterySkill), 1)] 
    public class ShaleBrickRecipe :
        RecipeFamily
    {
        public ShaleBrickRecipe()
        {
            this.Initialize(Localizer.DoStr("Shale Brick"), typeof(ShaleBrickRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "ShaleBrick",
                    Localizer.DoStr("Shale Brick"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(CrushedShaleItem), 1, typeof(PotterySkill), typeof(PotteryLavishResourcesTalent)), 
               new IngredientElement(typeof(ClayItem), 1, typeof(PotterySkill), typeof(PotteryLavishResourcesTalent)), 
               new IngredientElement(typeof(MortarItem), 8, typeof(PotterySkill), typeof(PotteryLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<BrickItem>(2),  
    
                    })
            };
            this.ExperienceOnCraft = 2;  
            this.LaborInCalories = CreateLaborInCaloriesValue(40, typeof(PotterySkill), typeof(ShaleBrickRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(ShaleBrickRecipe), this.UILink(), 1, typeof(PotterySkill), typeof(PotteryFocusedSpeedTalent), typeof(PotteryParallelSpeedTalent));     
            CraftingComponent.AddRecipe(typeof(KilnObject), this);
        }
    }
}
