// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    public class ShredKelpRecipe :
        RecipeFamily
    {
        public ShredKelpRecipe()
        {
            this.Initialize(Localizer.DoStr("Shred Kelp"), typeof(ShredKelpRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "ShredKelp",
                    Localizer.DoStr("Shred Kelp"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(KelpItem), 8),   
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<PlantFibersItem>(7),  
                    })
            };
            this.LaborInCalories = CreateLaborInCaloriesValue(40); 
            this.CraftMinutes = CreateCraftTimeValue(1);
            CraftingComponent.AddRecipe(typeof(FisheryObject), this);
        }
    }
}
