// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    [RequiresSkill(typeof(SmeltingSkill), 1)] 
    public class SmeltGoldRecipe :
        RecipeFamily
    {
        public SmeltGoldRecipe()
        {
            this.Initialize(Localizer.DoStr("Smelt Gold"), typeof(SmeltGoldRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "SmeltGold",
                    Localizer.DoStr("Smelt Gold"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(GoldConcentrateItem), 2, typeof(SmeltingSkill), typeof(SmeltingLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<GoldBarItem>(3),  
               new CraftingElement<SlagItem>(typeof(SmeltingSkill), 2, typeof(SmeltingLavishResourcesTalent)),     
                    })
            };
            this.ExperienceOnCraft = 2;  
            this.LaborInCalories = CreateLaborInCaloriesValue(100, typeof(SmeltingSkill), typeof(SmeltGoldRecipe), this.UILink()); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(SmeltGoldRecipe), this.UILink(), 4, typeof(SmeltingSkill), typeof(SmeltingFocusedSpeedTalent), typeof(SmeltingParallelSpeedTalent));     
            CraftingComponent.AddRecipe(typeof(BloomeryObject), this);
        }
    }
}
