// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Core.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;

    public partial class DirtRampRecipe :
        RecipeFamily
    {
        public DirtRampRecipe()
        {
            this.Initialize(Localizer.DoStr("Dirt Ramp"), typeof(DirtRampRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "DirtRamp",
                    Localizer.DoStr("Dirt Ramp"),
                    new IngredientElement[]
                    {
                    new IngredientElement(typeof(DirtItem), 6),   
                    },
                    new CraftingElement[]
                    {
                    new CraftingElement<DirtRampItem>(),  
                    }
                )
            };
            this.LaborInCalories = CreateLaborInCaloriesValue(20); 
            this.CraftMinutes = CreateCraftTimeValue(0.5f);
            this.Initialize(Localizer.DoStr("Dirt Ramp"), typeof(DirtRampRecipe));

            CraftingComponent.AddRecipe(typeof(WainwrightTableObject), this);

        }
    }

    [Serialized]
    [Constructed]
    [Road(1f)]                                           
    public partial class DirtRampBlock :
        Block            
    {
    }

}
