// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Core.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;

    [RequiresSkill(typeof(GlassworkingSkill), 1)]
    public partial class GlassRecipe :
        RecipeFamily
    {
        public GlassRecipe()
        {
            this.Initialize(Localizer.DoStr("Glass"), typeof(GlassRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "Glass",
                    Localizer.DoStr("Glass"),
                    new IngredientElement[]
                    {
                    new IngredientElement(typeof(SandItem), 3, typeof(GlassworkingSkill), typeof(GlassworkingLavishResourcesTalent)),
                    },
                    new CraftingElement[]
                    {
                    new CraftingElement<GlassItem>(),
                    }
                )
            };
            this.LaborInCalories = CreateLaborInCaloriesValue(50, typeof(GlassworkingSkill), typeof(GlassRecipe), this.UILink());
            this.ExperienceOnCraft = 1;
            this.CraftMinutes = CreateCraftTimeValue(typeof(GlassRecipe), this.UILink(), 1.5f, typeof(GlassworkingSkill), typeof(GlassworkingFocusedSpeedTalent), typeof(GlassworkingParallelSpeedTalent));
            this.Initialize(Localizer.DoStr("Glass"), typeof(GlassRecipe));

            CraftingComponent.AddRecipe(typeof(KilnObject), this);

        }
    }

    [Serialized]
    [Solid, Wall, Constructed,BuildRoomMaterialOption]
    [BlockTier(2)]
    [DoesntEncase]
    [RequiresSkill(typeof(GlassworkingSkill), 1)]
    public partial class GlassBlock :
        Block
        , IRepresentsItem
    {
        public Type RepresentedItemType { get { return typeof(GlassItem); } }
    }

    [Serialized]
    [LocDisplayName("Glass")]
    [MaxStackSize(40)]
    [Weight(10000)]
    [Ecopedia("Blocks", "Building Materials", createAsSubPage: true, display: InPageTooltip.DynamicTooltip)]
    [Currency]
    [Tag("Constructable", 1)]
    [Tier(2)]
    public partial class GlassItem :
    BlockItem<GlassBlock>
    {
        public override LocString DisplayNamePlural { get { return Localizer.DoStr("Glass"); } }
        public override LocString DisplayDescription { get { return Localizer.DoStr("A transparent, solid material useful for more than just windows."); } }

        public override bool CanStickToWalls { get { return false; } }

        private static Type[] blockTypes = new Type[] {
        typeof(GlassStacked1Block),
        typeof(GlassStacked2Block),
        typeof(GlassStacked3Block),
            typeof(GlassStacked4Block)
        };
        public override Type[] BlockTypes { get { return blockTypes; } }
    }

    [Serialized, Solid] public class GlassStacked1Block : PickupableBlock { }
    [Serialized, Solid] public class GlassStacked2Block : PickupableBlock { }
    [Serialized, Solid] public class GlassStacked3Block : PickupableBlock { }
    [Serialized, Solid,Wall] public class GlassStacked4Block : PickupableBlock { } //Only a wall if it's all 4 Glass
}
