// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Core.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;

    [RequiresSkill(typeof(BasicEngineeringSkill), 1)]      
    public partial class StoneRampRecipe :
        RecipeFamily
    {
        public StoneRampRecipe()
        {
            this.Initialize(Localizer.DoStr("Stone Ramp"), typeof(StoneRampRecipe));
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "StoneRamp",
                    Localizer.DoStr("Stone Ramp"),
                    new IngredientElement[]
                    {
                    new IngredientElement(typeof(MortarItem), 6, typeof(BasicEngineeringSkill), typeof(BasicEngineeringLavishResourcesTalent)),    
                    new IngredientElement("CrushedRock", 3, typeof(BasicEngineeringSkill), typeof(BasicEngineeringLavishResourcesTalent)),    
                    },
                    new CraftingElement[]
                    {
                    new CraftingElement<StoneRampItem>(),  
                    }
                )
            };
            this.LaborInCalories = CreateLaborInCaloriesValue(100, typeof(BasicEngineeringSkill), typeof(StoneRampRecipe), this.UILink()); 
            this.ExperienceOnCraft = 1;  
            this.CraftMinutes = CreateCraftTimeValue(typeof(StoneRampRecipe), this.UILink(), 0.5f, typeof(BasicEngineeringSkill), typeof(BasicEngineeringFocusedSpeedTalent), typeof(BasicEngineeringParallelSpeedTalent));     
            this.Initialize(Localizer.DoStr("Stone Ramp"), typeof(StoneRampRecipe));

            CraftingComponent.AddRecipe(typeof(WainwrightTableObject), this);

        }
    }

    [Serialized]
    [Constructed]
    [Road(1.2f)]                                           
    [RequiresSkill(typeof(BasicEngineeringSkill), 1)]      
    public partial class StoneRampBlock :
        Block            
    {
    }

}
